package com;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;



@Entity
public class Batch {

	
	@Id
	private String bcode;   //autogenerated we dont write because its datatype is String
	private String sub;
	private String trainer;
	private String timming;
	private int noOfStudent;
	
	//@OneToMany   //one batch consist of many student
	
	@OneToMany(mappedBy="batch")
	private List <Student> students;  //   for many student i created a list collection to student

	public String getBcode() {
		return bcode;
	}

	public void setBcode(String bcode) {
		this.bcode = bcode;
	}

	public String getSub() {
		return sub;
	}

	public void setSub(String sub) {
		this.sub = sub;
	}

	public String getTrainer() {
		return trainer;
	}

	public void setTrainer(String trainer) {
		this.trainer = trainer;
	}

	public String getTimming() {
		return timming;
	}

	public void setTimming(String timming) {
		this.timming = timming;
	}

	public int getNoOfStudent() {
		return noOfStudent;
	}

	public void setNoOfStudent(int noOfStudent) {
		this.noOfStudent = noOfStudent;
	}

	public List<Student> getStudents() {
		return students;
	}

	public void setStudents(List<Student> students) {
		this.students = students;
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
}
